name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # (Optional) Use Ccache or a specific compiler version
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake g++

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: cmake --build build --target unit-tests

      - name: Debug build Static Analysis (Clang-Tidy)
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CLANG_TIDY=clang-tidy .
          cmake --build build

      - name: Release build Static Analysis (Clang-Tidy)
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_CLANG_TIDY=clang-tidy .
          cmake --build build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build and run unit tests
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Coverage
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_TEST_COVERAGE=ON .
          cmake --build build
          ctest --test-dir build
